 // posts-data.js

const POSTS_DATA = [
  { title: "Best guest posting service 2026", link: "/best-guest-posting-service.html", category: "guest-posting" },
  { title: "Guest Posting Outreach", link: "/guest-posting-outreach.html", category: "guest-posting" },
  { title: "Guest Post link building", link: "/guest-post-link-building.html", category: "guest-posting" },
  { title: "Blogs that accept guest posts", link: "/blogs-that-accept-guest-posts.html", category: "guest-posting" },
  { title: "Where to get guest posts", link: "/where-to-get-guest-posts-for-addiction-center.html" , category: "guest-posting"},
  { title: "High authority guest posts", link: "/high-authority-guest-posts.html", category: "guest-posting" },
  { title: "Real estate guest posts", link: "/real-estate-guest-post.html", category: "guest-posting" },
  { title: "Technology guest posts", link: "/technology-guest-post.html", category: "guest-posting" },
  { title: "Sports guest posts", link: "/sports-guest-post.html" , category: "guest-posting"},
  { title: "White label guest posts", link: "/white-label-guest-posts.html", category: "guest-posting" },
  { title: "Guest posts Vs niche edits", link: "/guest-posting-vs-niche-edits.html" , category: "guest-posting"},
  { title: "Dofollow guest post guide", link: "/dofollow-guest-post-guide.html", category: "guest-posting" },
   { title: "Blogger Outreach Case Study", link: "/blogger-outreach-case-study.html", category: "guest-posting" }, 
   { title: "Guest Post & Blogger Outreach Service 2026", link: "/guest-post-blogger-outreach-service-2026.html", category: "guest-posting" }, 
 { title: "Buy link insertions", link: "/buy-link-insertions.html", category: "guest-posting" },
 { title: "Outreach Response Rate Increase Tips", link: "/outreach-response-rate-increase-tips-for-2026-seo.html", category: "guest-posting" },
  { title: "How to Pitch Bloggers Effectively", link: "/how-to-pitch-bloggers-effectively.html", category: "guest-posting" },
 { title: "Blogger Outreach White Label Service in 2026", link: "/blogger-outreach-white-label-service-2026.html", category: "guest-posting" },
  { title: "Is Guest Posting White Hat or Grey Hat SEO", link: "/is-guest-posting-white-hat-or-grey-hat-seo.html", category: "guest-posting" },
  { title: "SEO backlink strategy in 2026", link: "/seo-backlink-strategy-2026.html", category: "guest-posting" },
 { title: "Link building pr vs digital pr", link: "/link-building-pr-vs-digital-pr.html", category: "guest-posting" },
{ title: "Shopify Link Building Strategy 2026", link: "/shopify-link-building-strategy-2026.html", category: "guest-posting" },
{ title: "Link building for new Shopify website", link: "/link-building-for-new-shopify-website.html", category: "guest-posting" },
{ title: "Local SEO Guest Posting Strategy", link: "/local-seo-guest-posting-strategy.html", category: "guest-posting" },
{ title: "Content Writing for Guest Posts", link: "/content-writing-for-guest-posts.html", category: "guest-posting" },
{ title: "Health blogs that accept guest posts", link: "/health-blogs-that-accept-guest-posts.html", category: "guest-posting" },
{ title: "Broken Link Building Strategy", link: "/broken-link-building-strategy.html", category: "guest-posting" },
{ title: "How to Sell Guest Posting Services on Fiverr", link: "/how-to-sell-guest-posting-services-on-fiverr.html", category: "guest-posting" },
{ title: "Competitor Backlink Spying Strategy", link: "/competitor-backlink-spying-strategy.html", category: "guest-posting" },
{ title: "How to follow up guest post pitch without spam", link: "/how-to-follow-up-guest-post-pitch-without-spam.html", category: "guest-posting" },
{ title: "Guest post acceptance rate improvement techniques", link: "/guest-post-acceptance-rate-improvement-techniques.html", category: "guest-posting" },
{ title: "Common guest posting outreach mistakes for beginners", link: "/common-guest-posting-outreach-mistakes-for-beginners.html", category: "guest-posting" },
{ title: "How Many Backlinks Per Guest Post Is Safe?", link: "/how-many-backlinks-per-guest-post-is-safe.html", category: "guest-posting" },
{ title: "Guest post topic research method step by step", link: "/guest-post-topic-research-method-step-by-step.html", category: "guest-posting" },
{ title: "Guest post link decay", link: "/guest-post-link-decay.html", category: "guest-posting" },
{ title: "Guest posting ROI calculation method", link: "/guest-posting-roi-calculation-method.html", category: "guest-posting" },
{ title: "How to qualify websites for guest posting", link: "/how-to-qualify-websites-for-guest-posting.html", category: "guest-posting" },
{ title: "Guest post pricing per domain authority explained", link: "/guest-post-pricing-per-domain-authority-explained.html", category: "guest-posting" },
{ title: "Pros and cons of blogging", link: "/pros-and-cons-of-blogging.html", category: "guest-posting" },
{ title: "How to do outreach for guest posting", link: "/how-to-do-outreach-for-guest-posting.html", category: "guest-posting" },
{ title: "How to get clients for guest posting", link: "/how-to-get-clients-for-guest-posting.html", category: "guest-posting" },
{ title: "How to do guest posting step by step", link: "/how-to-do-guest-posting-step-by-step.html", category: "guest-posting" },
{ title: "How many guest posts per month is ideal", link: "/how-many-guest-posts-per-month-is-ideal.html", category: "guest-posting" },
{ title: "How to Create Backlinks Step by Step Free", link: "/how-to-create-backlinks-step-by-step-free.html", category: "guest-posting" },
{ title: "SEO backlink strategies for beginners", link: "/seo-backlink-strategies-for-beginners.html", category: "guest-posting" },
{ title: "Free guest posting sites without registration", link: "/free-guest-posting-sites-without-registration.html", category: "guest-posting" },
{ title: "Difference between blogger outreach and guest posting", link: "/what-is-the-difference-between-blogger-outreach-and-guest-posting.html", category: "guest-posting" },
{ title: "How to get backlinks through guest posting step by step", link: "/how-to-get-backlinks-through-guest-posting-step-by-step.html", category: "guest-posting" },
{ title: "Difference between editorial links and guest posts", link: "/difference-between-editorial-links-and-guest-posts.html", category: "guest-posting" },
{ title: "Does Google count guest post backlinks", link: "/does-google-count-guest-post-backlinks.html", category: "guest-posting" },
{ title: "How to find niche blogs for guest posting", link: "/how-to-find-niche-blogs-for-guest-posting", category: "guest-posting" },
{ title: "How to avoid spam in guest posting", link: "/how-to-avoid-spam-in-guest-posting", category: "guest-posting" }

 ];
